### ISSUE TITLE
Browser prompts to download ePub instead of displaying it

### ISSUE THREAD

**Issue by hilongo** [lepidus/epubViewer#1]
Hello !

I have installed the Bibi ePub viewer plugin in OJS versions 3.3.0.8 and 3.3.0.13 via the plugin gallery but whenever I try to view an ePub galley the browser prompts me to download the file instead of displaying it as with the PDF galleys.

Is there something else to do to make the plugin work, aside of just install it? It does not have any option to ‘configure’ from the plugin’s information section

Maybe some extra step in the ePub galley upload step?

Thanks in advance!

**Comment by pablovp86** [comment]
Hi, @hilongo.

Our team is investigating your report, we will provide feedback as soon as possible.

**Comment by pablovp86** [comment]
Hi, @hilongo.

We are having difficulty reproducing the reported issue.

Can you please provide more information related to the context where you are experiencing it? 

Information like:

-  PHP version of the running OJS instance
-  OJS instance URL
- A link to an ePub file

Could help us into further investigation.

**Comment by diegoabadan** [comment]
@hilongo , please let us know if you can provide more information. For now, we will close this issue.
