### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by JackieHeCc** [lepidus/epubViewer#2]
After I uploaded the epub file of an article, I activated the epubViewer plug-in in the background plug-in. When I clicked on the epub Galley in the journal article file list, an error message popped up: "TypeError: Cannot read properties of undefined (reading 'getAttribute') ", how do I locate this error message?

**Comment by YvesCesar** [comment]
Hi, @JackieHeCc :smiley: 

Can you please provide more information related to the context where you are experiencing it?

Information like:

- PHP version of the running OJS (or OMP) instance
- OJS (or OMP) instance URL
- A link to an ePub file

**Comment by JackieHeCc** [comment]
@YvesCesar

Thanks for your response, you can see the specific situation through this link: [epub](https://www.hksmp.com/journals/prm/article/view/452/485)。

**Comment by diegoabadan** [comment]
We've r[eleased a new version](https://github.com/lepidus/epubViewer/releases) of the plugin, but it doesn't seem to fully resolve the reported problem.

We have verified that other users have reported the same behavior in the Bibi ePUB reader that we use in the plugin. However, this reader seems to be discontinued: https://github.com/satorumurmur/bibi

We'll evaluate replacing Bibi with a better maintained ePub reader. However, we don't have an estimate of when we'll be able to do this

**Comment by JackieHeCc** [comment]
@diegoabadan Thanks for your response, I found another OJS plug-in from Github that can parse our epub normally.

Best regards.

**Comment by bvisonl** [comment]
> [@diegoabadan](https://github.com/diegoabadan) Thanks for your response, I found another OJS plug-in from Github that can parse our epub normally.
> 
> Best regards.

Can you share your plugin?

**Comment by diegoabadan** [comment]
The only other one I know of is for OJS 3.2:
https://github.com/EKT/epubJsViewer-ojs

It hasn't been updated for 5 years.

**Comment by bvisonl** [comment]
> The only other one I know of is for OJS 3.2: https://github.com/EKT/epubJsViewer-ojs
> 
> It hasn't been updated for 5 years.

Thanks, I installed that one and it worked 👍🏻

**Comment by marcbria** [comment]
**Update:** Not sure when and how but the epub plugin included in the gallery is working great on OJS 3.3.

https://analisi.cat/article/view/v73-martin-neira-etal

Cheers,
m.
